Attribute VB_Name = "modMenuDefinitions"
Option Explicit

'13/01/2009 - mpdea
'Constantes para uso do menu
'
'27/01/2009 - mpdea
'Concluído versão inicial

'IDs de sistema
Public Const FSHIFT = 4
Public Const FCONTROL = 8
Public Const FALT = 16

Public Const ID_INDICATOR_CAPS = 59137
Public Const ID_INDICATOR_NUM = 59138
Public Const ID_INDICATOR_SCRL = 59139

Public Const ID_APP_EXIT As Long = 57665
'Public Const ID_WINDOW_SWITCH as long = 143

'IDs válidos de 100 a 5700

'Regras para numeração de ID
'
'TAB    - De 101 a 110
'GROUP  - De 201 a 300 (Intervalo de 10 para TAB diferente)
'POPUP  - De 301 a 1000 (Intervalo de 50 para TAB diferente)
'ITEM   - De 1001 a 5000 (Intervalo de 100 para TAB diferente)
'OUTROS - De 5000 a 5700

Public Const ID_SYSTEM_CONTROL As Long = 5000
Public Const ID_SYSTEM_ICON As Long = 5001

'STATUSBAR
Public Const ID_STATUSBAR_FILIAL As Long = 5500
Public Const ID_STATUSBAR_USUARIO As Long = 5501
Public Const ID_STATUSBAR_VERSAO As Long = 5502

'TAB
Public Const ID_TAB_INICIO As Long = 101
Public Const ID_TAB_CADASTRO As Long = 102
Public Const ID_TAB_MOVIMENTO As Long = 103
Public Const ID_TAB_FINANCEIRO As Long = 104
Public Const ID_TAB_PRECO As Long = 105
Public Const ID_TAB_ESTOQUE As Long = 106
Public Const ID_TAB_GERADOR As Long = 107
Public Const ID_TAB_RELATORIO As Long = 108

'GROUP
Public Const ID_GROUP_INICIO_AREA_TRANSF As Long = 201
Public Const ID_GROUP_INICIO_GERAL As Long = 202
Public Const ID_GROUP_INICIO_PARAMETROS As Long = 203
Public Const ID_GROUP_INICIO_SUPLEMENTO As Long = 204
Public Const ID_GROUP_INICIO_GESTAO As Long = 205
Public Const ID_GROUP_INICIO_STANDBY As Long = 206
Public Const ID_GROUP_HELP_QUICK As Long = 207

Public Const ID_GROUP_CADASTRO_GERAL As Long = 211
Public Const ID_GROUP_CADASTRO_MALA_DIRETA As Long = 212
Public Const ID_GROUP_CADASTRO_OPERACAO As Long = 213
Public Const ID_GROUP_CADASTRO_SUPLEMENTO As Long = 214

Public Const ID_GROUP_MOVIMENTO_GERAL As Long = 221
Public Const ID_GROUP_MOVIMENTO_SUPLEMENTO As Long = 222

Public Const ID_GROUP_FINANCEIRO_CC As Long = 231
Public Const ID_GROUP_FINANCEIRO_CAIXA As Long = 232
Public Const ID_GROUP_FINANCEIRO_CONTAS_PAGAR As Long = 233
Public Const ID_GROUP_FINANCEIRO_CONTAS_RECEBER As Long = 234
Public Const ID_GROUP_FINANCEIRO_SUPLEMENTO As Long = 235

Public Const ID_GROUP_PRECO_GERAL As Long = 241
Public Const ID_GROUP_PRECO_COPIAR_TABELA As Long = 242
Public Const ID_GROUP_PRECO_CALCULAR As Long = 243

Public Const ID_GROUP_ESTOQUE_NORMAL As Long = 251
Public Const ID_GROUP_ESTOQUE_GRADE As Long = 252

Public Const ID_GROUP_GERADOR_GERAL As Long = 261
Public Const ID_GROUP_GERADOR_SUPLEMENTO As Long = 262

Public Const ID_GROUP_RELATORIO_GERAL As Long = 271
Public Const ID_GROUP_RELATORIO_SUPLEMENTO As Long = 272

'POPUP
Public Const ID_POPUP_AJUDA_AJUDA As Long = 301

Public Const ID_POPUP_SUPLEMENTO As Long = 351

'Public Const ID_POPUP_INICIO_SUPLEMENTO as long = 401

'Public Const ID_POPUP_CADASTRO_PESSOA As Long = 451
Public Const ID_POPUP_CADASTRO_PESSOA As Long = 29

Public Const ID_POPUP_CADASTRO_PRODUTO As Long = 452
Public Const ID_POPUP_CADASTRO_PESQUISA As Long = 453
Public Const ID_POPUP_CADASTRO_FINANCEIRO As Long = 454
Public Const ID_POPUP_CADASTRO_MALA_DIRETA As Long = 455
'Public Const ID_POPUP_CADASTRO_SUPLEMENTO as long = 456
Public Const ID_POPUP_CADASTRO_PROGRAMA_FIDELIDADE As Long = 457

Public Const ID_POPUP_MOVIMENTO_TRANSFERENCIA As Long = 501
Public Const ID_POPUP_MOVIMENTO_EMPRESTIMO As Long = 502
Public Const ID_POPUP_MOVIMENTO_MANUT As Long = 503
'Public Const ID_POPUP_MOVIMENTO_SUPLEMENTO as long = 504

Public Const ID_POPUP_FINANCEIRO_CP_MOVIMENTO As Long = 551
Public Const ID_POPUP_FINANCEIRO_CR_MOVIMENTO As Long = 552
Public Const ID_POPUP_FINANCEIRO_CR_CHEQUE_PRE As Long = 553
Public Const ID_POPUP_FINANCEIRO_CR_CARTAO As Long = 554
Public Const ID_POPUP_FINANCEIRO_CR_CONTA_CLIENTE As Long = 555
'Public Const ID_POPUP_FINANCEIRO_SUPLEMENTO as long = 556

'Public Const ID_POPUP_GERADOR_SUPLEMENTO as long = 601

Public Const ID_POPUP_RELATORIO_SERVICO As Long = 651
Public Const ID_POPUP_RELATORIO_PRODUTO As Long = 652
Public Const ID_POPUP_RELATORIO_ESTOQUE As Long = 653
Public Const ID_POPUP_RELATORIO_COMPRA_VENDA As Long = 654
Public Const ID_POPUP_RELATORIO_MOVIMENTO As Long = 655
Public Const ID_POPUP_RELATORIO_CLIETE_FORNECEDOR As Long = 656
Public Const ID_POPUP_RELATORIO_USUARIO As Long = 657
Public Const ID_POPUP_RELATORIO_CADASTRO As Long = 658
Public Const ID_POPUP_RELATORIO_FINANCEIRO As Long = 659
Public Const ID_POPUP_RELATORIO_FINANC_CONTA_PAGAR As Long = 660
Public Const ID_POPUP_RELATORIO_FINANC_CONTA_RECEBER As Long = 661
Public Const ID_POPUP_RELATORIO_GRAFICO As Long = 662
Public Const ID_POPUP_RELATORIO_PRECO As Long = 663
'Public Const ID_POPUP_RELATORIO_SUPLEMENTO as long = 664

'ITEM
Public Const ID_ITEM_ARQUIVO_ESTACOES_CONECTADAS As Long = 1001
Public Const ID_ITEM_ARQUIVO_LOGON As Long = 1002
Public Const ID_ITEM_ARQUIVO_COMPACTAR_BASE As Long = 1003
Public Const ID_ITEM_ARQUIVO_REPARAR_BASE As Long = 1004
Public Const ID_ITEM_ARQUIVO_EXPORTAR_BASE As Long = 1005
Public Const ID_ITEM_ARQUIVO_BACKUP As Long = 1006

Public Const ID_ITEM_AJUDA_CONTEUDO As Long = 1101
Public Const ID_ITEM_AJUDA_PESQUISA As Long = 1102
Public Const ID_ITEM_AJUDA_SOBRE As Long = 1103
Public Const ID_ITEM_AJUDA_REGISTRO As Long = 1104
Public Const ID_ITEM_AJUDA_INSTITUCIONAL As Long = 1105
Public Const ID_ITEM_AJUDA_AGENDA As Long = 1106

Public Const ID_ITEM_REL_SAIDAS_ENTRADAS As Long = 1201
'''Public Const ID_ITEM_INICIO_COLAR As Long = 1201
'''Public Const ID_ITEM_INICIO_RECORTAR As Long = 1202
'''Public Const ID_ITEM_INICIO_COPIAR As Long = 1203
Public Const ID_ITEM_INICIO_LIVRO_PONTO As Long = 1204
Public Const ID_ITEM_INICIO_PARAM_EMPRESA As Long = 1205
Public Const ID_ITEM_INICIO_PARAM_IMPOSTO_ESTADUAL As Long = 1206
Public Const ID_ITEM_INICIO_PARAM_CONFIG_IMPRESSORA As Long = 1207
Public Const ID_ITEM_INICIO_PARAM_CLASS_CLIENTE As Long = 1208
Public Const ID_ITEM_INICIO_PARAM_FATURAMENTO_AUTO As Long = 1209
Public Const ID_ITEM_INICIO_PARAM_DEVOL_MATERIAL As Long = 1210
Public Const ID_ITEM_INICIO_PARAM_TEMA As Long = 1211
Public Const ID_ITEM_INICIO_PARAM_TEMA_AZUL As Long = 1212
Public Const ID_ITEM_INICIO_PARAM_TEMA_AQUA As Long = 1213
Public Const ID_ITEM_INICIO_PARAM_TEMA_PRETO As Long = 1214
Public Const ID_ITEM_INICIO_COCKPIT As Long = 1215
Public Const ID_ITEM_INICIO_STANDBY As Long = 1216
'''Public Const ID_ACESSO_HELP_QUICK = 1217

Public Const ID_ITEM_CADASTRO_SERVICO As Long = 1301
Public Const ID_ITEM_CADASTRO_PRODUTO As Long = 1302
Public Const ID_ITEM_CADASTRO_CLIENTE_FORNEC As Long = 1303
Public Const ID_ITEM_CADASTRO_CARACT_CLIENTE_FORNEC As Long = 1304
Public Const ID_ITEM_CADASTRO_TRANSPORTADORA As Long = 1305
Public Const ID_ITEM_CADASTRO_USUARIO As Long = 1306
Public Const ID_ITEM_CADASTRO_CLASSE As Long = 1307
Public Const ID_ITEM_CADASTRO_SUBCLASSE As Long = 1308
Public Const ID_ITEM_CADASTRO_COR As Long = 1309
Public Const ID_ITEM_CADASTRO_TAMANHO As Long = 1310
Public Const ID_ITEM_CADASTRO_ETIQUETA_PRODUTO As Long = 1311
Public Const ID_ITEM_CADASTRO_PESQUISA_1 As Long = 1312
Public Const ID_ITEM_CADASTRO_PESQUISA_2 As Long = 1313
Public Const ID_ITEM_CADASTRO_PESQUISA_3 As Long = 1314
Public Const ID_ITEM_CADASTRO_BANCO As Long = 1315
Public Const ID_ITEM_CADASTRO_CONTA_CORRENTE As Long = 1316
Public Const ID_ITEM_CADASTRO_CARTAO As Long = 1317
Public Const ID_ITEM_CADASTRO_CAIXA As Long = 1318
Public Const ID_ITEM_CADASTRO_MOEDA As Long = 1319
Public Const ID_ITEM_CADASTRO_COTACAO As Long = 1320
Public Const ID_ITEM_CADASTRO_CLASSIFICACAO_FISCAL As Long = 1321
Public Const ID_ITEM_CADASTRO_CENTRO_CUSTO As Long = 1322
Public Const ID_ITEM_CADASTRO_RADIO As Long = 1323
Public Const ID_ITEM_CADASTRO_TIPO_COMERCIAL As Long = 1324
Public Const ID_ITEM_CADASTRO_AUT_PUBLICIDADE As Long = 1325
Public Const ID_ITEM_CADASTRO_SUPERVISOR As Long = 1326
Public Const ID_ITEM_CADASTRO_RETENCAO As Long = 1327
Public Const ID_ITEM_CADASTRO_CODIGO_NBM As Long = 1328
Public Const ID_ITEM_CADASTRO_GRUPO_FISCAL As Long = 1329
Public Const ID_ITEM_CADASTRO_MENSAGEM_NOTA_FISCAL As Long = 1330
Public Const ID_ITEM_CADASTRO_MALA_DIRETA_PREPARAR As Long = 1331
Public Const ID_ITEM_CADASTRO_MALA_DIRETA_MANUTENCAO As Long = 1332
Public Const ID_ITEM_CADASTRO_MALA_DIRETA_PREPARAR_REMETENTE As Long = 1333
Public Const ID_ITEM_CADASTRO_MALA_DIRETA_GRUPO As Long = 1334
Public Const ID_ITEM_CADASTRO_OPERACAO_ENTRADA As Long = 1335
Public Const ID_ITEM_CADASTRO_OPERACAO_SAIDA As Long = 1336
Public Const ID_ITEM_CADASTRO_PRODUTO_CFOP As Long = 1337
Public Const ID_ITEM_CADASTRO_PROGRAMA_FIDELIDADE As Long = 1338
Public Const ID_ITEM_CADASTRO_PROGRAMA_FIDELIDADE_OPERACOES_SAIDA As Long = 1339
Public Const ID_ITEM_CADASTRO_PROGRAMA_FIDELIDADE_CONSULTA_GERENCIAL As Long = 1340
Public Const ID_ITEM_CADASTRO_PROGRAMA_FIDELIDADE_RESGATE_PONTOS As Long = 1341
Public Const ID_ITEM_CADASTRO_PROGRAMA_FIDELIDADE_CLIENTE_ENTREGA_RESGATE As Long = 1342
Public Const ID_ITEM_CADASTRO_PROGRAMA_FIDELIDADE_CLIENTES_NAO_PART As Long = 1343
Public Const ID_ITEM_CADASTRO_PROGRAMA_FIDELIDADE_CNPJ_GRUPOS As Long = 1344
Public Const ID_ITEM_FORMATAR_ETIQUETA_PRODUTO As Long = 1345



Public Const ID_ITEM_MOVIMENTO_VENDA_RAPIDA As Long = 1401
Public Const ID_ITEM_MOVIMENTO_ENTRADAS As Long = 1402
Public Const ID_ITEM_MOVIMENTO_SAIDAS As Long = 1403
Public Const ID_ITEM_MOVIMENTO_ORDEM_SERVICO As Long = 1404
Public Const ID_ITEM_MOVIMENTO_PEDIDOS_WEB As Long = 1405
Public Const ID_ITEM_MOVIMENTO_MANUT_RESERVA As Long = 1406
Public Const ID_ITEM_MOVIMENTO_MANUT_CONSIG_ENTRADA As Long = 1407
Public Const ID_ITEM_MOVIMENTO_FATUR_AUTO As Long = 1408
Public Const ID_ITEM_MOVIMENTO_PREST_FORNEC As Long = 1409
Public Const ID_ITEM_MOVIMENTO_IMPORTACAO As Long = 1410
Public Const ID_ITEM_MOVIMENTO_APAGAR_EMP_ENTRADA As Long = 1411
Public Const ID_ITEM_MOVIMENTO_APAGAR_EMP_SAIDA As Long = 1412
Public Const ID_ITEM_MOVIMENTO_APAGAR_ENTRADA As Long = 1413
Public Const ID_ITEM_MOVIMENTO_APAGAR_SAIDA As Long = 1414
Public Const ID_ITEM_MOVIMENTO_APAGAR_MOVIMENTACAO As Long = 1415
Public Const ID_ITEM_MOVIMENTO_MANUT_CONSIGNACAO As Long = 1416
Public Const ID_ITEM_MOVIMENTO_MANUT_ORCAMENTO As Long = 1417
Public Const ID_ITEM_MOVIMENTO_TRANSF_FILIAL As Long = 1418
Public Const ID_ITEM_MOVIMENTO_EMPREST_ENTRADA As Long = 1419
Public Const ID_ITEM_MOVIMENTO_EMPREST_SAIDA As Long = 1420
'14/09/2009 - mpdea
Public Const ID_ITEM_MOVIMENTO_NOTA_FISCAL_ELETRONICA As Long = 1421
Public Const ID_IMPORTA_GESTO As Long = 1422
Public Const ID_ITEM_MOVIMENTO_DEVOLUCOES As Long = 1423

Public Const ID_ITEM_PRECO_CRIAR_TAB As Long = 1501
Public Const ID_ITEM_PRECO_APAGAR_TAB As Long = 1502
Public Const ID_ITEM_PRECO_LANCAR As Long = 1503
Public Const ID_ITEM_PRECO_ALTERAR As Long = 1504
Public Const ID_ITEM_PRECO_ALTERAR_CALC As Long = 1505
Public Const ID_ITEM_PRECO_CONFIG_TAB As Long = 1506
Public Const ID_ITEM_PRECO_COPIAR_TAB_IND As Long = 1507
Public Const ID_ITEM_PRECO_COPIAR_TAB_VALOR As Long = 1508
Public Const ID_ITEM_PRECO_COPIAR_TAB_CUSTO_MEDIO As Long = 1509
Public Const ID_ITEM_PRECO_CALC_PRECO As Long = 1510
Public Const ID_ITEM_PRECO_CALC_PRECO_SIMPLES As Long = 1511

Public Const ID_ITEM_ESTOQUE_INFO_CONTAR As Long = 1601
'''Public Const ID_ITEM_ESTOQUE_ACERTAR_CONTAR As Long = 1602
Public Const ID_ITEM_ESTOQUE_INFO_CONTAR_GRADE As Long = 1603
Public Const ID_ITEM_ESTOQUE_ACERTAR_CONTAR_GRADE As Long = 1604

Public Const ID_ITEM_FINANCEIRO_MOV_MANUAL_CAIXA As Long = 1701
Public Const ID_ITEM_FINANCEIRO_APAGA_LANC_CAIXA As Long = 1702
Public Const ID_ITEM_FINANCEIRO_LANC_BANC As Long = 1703
Public Const ID_ITEM_FINANCEIRO_RECAL_SALDO As Long = 1704
Public Const ID_ITEM_FINANCEIRO_APAGA_LANC_BANC As Long = 1705
Public Const ID_ITEM_FINANCEIRO_CP_LANCAR As Long = 1706
Public Const ID_ITEM_FINANCEIRO_CP_GERAR As Long = 1707
Public Const ID_ITEM_FINANCEIRO_CP_MANUT As Long = 1708
Public Const ID_ITEM_FINANCEIRO_CP_APAGAR_PAGA As Long = 1709
Public Const ID_ITEM_FINANCEIRO_CR_LANCAR As Long = 1710
Public Const ID_ITEM_FINANCEIRO_CR_MANUT As Long = 1711
Public Const ID_ITEM_FINANCEIRO_CR_APAGAR_RECEBIDA As Long = 1712
Public Const ID_ITEM_FINANCEIRO_CR_LANCAR_CHEQUE_PRE As Long = 1713
Public Const ID_ITEM_FINANCEIRO_CR_MANUT_CHEQUE_PRE As Long = 1714
Public Const ID_ITEM_FINANCEIRO_CR_APAGAR_CHEQUE_PRE As Long = 1715
Public Const ID_ITEM_FINANCEIRO_CR_LANCAR_CARTAO As Long = 1716
Public Const ID_ITEM_FINANCEIRO_CR_MANUT_CARTAO As Long = 1717
Public Const ID_ITEM_FINANCEIRO_CR_APAGAR_CARTAO As Long = 1718
Public Const ID_ITEM_FINANCEIRO_CR_LANCAR_CONTA_CLIENTE As Long = 1719
Public Const ID_ITEM_FINANCEIRO_CR_MANUT_CONTA_CLIENTE As Long = 1720
Public Const ID_ITEM_FINANCEIRO_CR_APAGAR_CONTA_CLIENTE As Long = 1721
Public Const ID_ITEM_FINANCEIRO_CR_AUT_PUBLICIDADE As Long = 1722

Public Const ID_ITEM_GERADOR_RELATORIO As Long = 1801
Public Const ID_ITEM_GERADOR_LAYOUT_NOTA As Long = 1802
Public Const ID_ITEM_GERADOR_LAYOUT_TICKET As Long = 1803
Public Const ID_ITEM_GERADOR_LAYOUT_BOLETO As Long = 1804
Public Const ID_ITEM_GERADOR_LAYOUT_CARNET As Long = 1805
Public Const ID_ITEM_GERADOR_ARQ_REC_ESTADUAL As Long = 1806
Public Const ID_ITEM_GERADOR_EXP_BR_INFO As Long = 1807
Public Const ID_ITEM_GERADOR_EXP_SADIG_WEB As Long = 1808
Public Const ID_ITEM_GERADOR_EXP_PEARSON As Long = 1809

Public Const ID_ITEM_REL_SERVICO_EXECUTADO As Long = 1901
Public Const ID_ITEM_REL_SERVICO_COMISSAO As Long = 1902
Public Const ID_ITEM_REL_PRODUTO_GERAL As Long = 1903
Public Const ID_ITEM_REL_PRODUTO_GRADE As Long = 1904
Public Const ID_ITEM_REL_ESTOQUE_GERAL As Long = 1905
Public Const ID_ITEM_REL_ESTOQUE_GRADE As Long = 1906
Public Const ID_ITEM_REL_ESTOQUE_ANALITICO As Long = 1907
Public Const ID_ITEM_REL_ESTOQUE_POR_FILIAL As Long = 1908
Public Const ID_ITEM_REL_ESTOQUE_FILIAL_PRECO As Long = 1909
Public Const ID_ITEM_REL_ESTOQUE_PRODUTO_COMPRAR As Long = 1910
Public Const ID_ITEM_REL_ESTOQUE_ACOMPANHAMENTO_PRODUTO As Long = 1911
Public Const ID_ITEM_REL_ESTOQUE_ACOMPANHAMENTO_ESTOQUE As Long = 1912
Public Const ID_ITEM_REL_ESTOQUE_REGISTRO_INVENTARIO As Long = 1913
Public Const ID_ITEM_REL_ESTOQUE_CONTAGEM As Long = 1914
Public Const ID_ITEM_REL_ESTOQUE_CONTAGEM_GRADE As Long = 1915
Public Const ID_ITEM_REL_CV_VENDA As Long = 1916
Public Const ID_ITEM_REL_CV_VENDA_2 As Long = 1917
Public Const ID_ITEM_REL_CV_COMISSAO As Long = 1918
Public Const ID_ITEM_REL_CV_COMISSAO_RETENCAO As Long = 1919
Public Const ID_ITEM_REL_CV_COMISSAO_VENDA_VENDEDOR As Long = 1920
Public Const ID_ITEM_REL_CV_COMPRAS As Long = 1921
Public Const ID_ITEM_REL_CV_PRODUTO_COMPRAR_FATOR As Long = 1922
Public Const ID_ITEM_REL_CV_VENDA_CLIENTE As Long = 1923
Public Const ID_ITEM_REL_CV_VENDA_VENDEDOR_COMISSAO As Long = 1924
Public Const ID_ITEM_REL_CV_VENDA_TAMANHO As Long = 1925
Public Const ID_ITEM_REL_CV_VENDA_EDITORA As Long = 1926
Public Const ID_ITEM_REL_CV_VENDA_FORNECEDOR As Long = 1927
Public Const ID_ITEM_REL_CV_VENDA_PRODUTO_CONSIGNADO As Long = 1928
Public Const ID_ITEM_REL_CV_PRESTACAO_CONTA As Long = 1929
Public Const ID_ITEM_REL_MOV_ENTRADA As Long = 1930
Public Const ID_ITEM_REL_MOV_SAIDA As Long = 1931
Public Const ID_ITEM_REL_MOV_ACERTA_EMPREST_ENTRADA As Long = 1932
Public Const ID_ITEM_REL_MOV_ACERTA_EMPREST_SAIDA As Long = 1933
Public Const ID_ITEM_REL_MOV_ENTRADA_CONSIGNADA As Long = 1934
Public Const ID_ITEM_REL_CLIENTE_FORNECEDOR As Long = 1935
Public Const ID_ITEM_REL_CONTATO_EFETUADO As Long = 1936
Public Const ID_ITEM_REL_CONTATO_DATA_ANIVERSARIO As Long = 1937
Public Const ID_ITEM_REL_USUARIO_FUNCIONARIO As Long = 1938
Public Const ID_ITEM_REL_LIVRO_PONTO As Long = 1939
Public Const ID_ITEM_REL_CADASTRO_CLASSE As Long = 1940
Public Const ID_ITEM_REL_CADASTRO_SUBCLASSE As Long = 1941
Public Const ID_ITEM_REL_CADASTRO_COR As Long = 1942
Public Const ID_ITEM_REL_CADASTRO_TAMANHO As Long = 1943
Public Const ID_ITEM_REL_CADASTRO_ETIQUETA_PRODUTO As Long = 1944
Public Const ID_ITEM_REL_CADASTRO_BANCO As Long = 1945
Public Const ID_ITEM_REL_CADASTRO_CARTAO As Long = 1946
Public Const ID_ITEM_REL_CADASTRO_MOEDA As Long = 1947
Public Const ID_ITEM_REL_CADASTRO_COTACAO As Long = 1948
Public Const ID_ITEM_REL_CADASTRO_CENTRO_CUSTO As Long = 1949
Public Const ID_ITEM_REL_FINANC_CAIXA As Long = 1950
Public Const ID_ITEM_REL_FINANC_CARTAO As Long = 1951
Public Const ID_ITEM_REL_FINANC_LANC_BANCARIO As Long = 1952
Public Const ID_ITEM_REL_FINANC_SALDO_CC As Long = 1953
Public Const ID_ITEM_REL_FINANC_DIARIO_1 As Long = 1954
Public Const ID_ITEM_REL_FINANC_DIARIO_2 As Long = 1955
Public Const ID_ITEM_REL_FINANC_LUCRATIVIDADE As Long = 1956
Public Const ID_ITEM_REL_FINANC_GERAL As Long = 1957
Public Const ID_ITEM_REL_FINANC_RECEB_FORMA_PGTO As Long = 1958
Public Const ID_ITEM_REL_FINANC_FLUXO_CAIXA As Long = 1959
Public Const ID_ITEM_REL_CP_PAGAR_DATA_VCTO As Long = 1960
Public Const ID_ITEM_REL_CP_PAGAR_FORNECEDOR As Long = 1961
Public Const ID_ITEM_REL_CP_PAGAR_GERAL_FILIAL As Long = 1962
Public Const ID_ITEM_REL_CP_PAGAR_CENTRO_CUSTO As Long = 1963
Public Const ID_ITEM_REL_CP_PAGAS_FORNECEDOR As Long = 1964
Public Const ID_ITEM_REL_CP_PAGAS_DATA_PGTO As Long = 1965
Public Const ID_ITEM_REL_CP_PAGAS_CENTRO_CUSTO As Long = 1966
Public Const ID_ITEM_REL_CP_CONTROLE_CENTRO_CUSTO As Long = 1967
Public Const ID_ITEM_REL_CP_CENTRO_CUSTO_COMPETENCIA As Long = 1968
Public Const ID_ITEM_REL_CR_RECEBER_DATA_VCTO As Long = 1969
Public Const ID_ITEM_REL_CR_RECEBER_CLIENTE As Long = 1970
Public Const ID_ITEM_REL_CR_RECEBER_VENDEDOR As Long = 1971
Public Const ID_ITEM_REL_CR_RECEBIDA_DATA_RECEBIMENTO As Long = 1972
Public Const ID_ITEM_REL_CR_RECEBIDA_VENDEDOR As Long = 1973
Public Const ID_ITEM_REL_CR_RECEBIDA_CLIENTE As Long = 1974
Public Const ID_ITEM_REL_CR_CHEQUE_PRE As Long = 1975
Public Const ID_ITEM_REL_CR_CARTAO As Long = 1976
Public Const ID_ITEM_REL_CR_CONTA_CLIENTE As Long = 1977
Public Const ID_ITEM_REL_CR_EMISSAO_BOLETO As Long = 1978
Public Const ID_ITEM_REL_CR_EMISSAO_CARNET As Long = 1979
Public Const ID_ITEM_REL_MALA_DIRETA As Long = 1980
Public Const ID_ITEM_REL_MALA_DIRETA_GERAR_ARQUIVO As Long = 1981
Public Const ID_ITEM_REL_FOLHA_PGTO As Long = 1982
Public Const ID_ITEM_REL_AUTORIZACAO As Long = 1983
Public Const ID_ITEM_REL_MALA_DIRETA_AUTORIZACAO As Long = 1984
Public Const ID_ITEM_REL_GRAFICO_COMPARATIVO_CV As Long = 1985
Public Const ID_ITEM_REL_GRAFICO_VENDA_CLASSE_PERIODO As Long = 1986
Public Const ID_ITEM_REL_GRAFICO_VENDA_PRODUTO_MENSAL As Long = 1987
Public Const ID_ITEM_REL_NSU_CORRELACAO As Long = 1988
Public Const ID_ITEM_REL_PRECO_LISTA As Long = 1989
Public Const ID_ITEM_REL_PRECO_LOCAL_PRODUTO As Long = 1990
Public Const ID_ITEM_REL_CV_VENDA_POR_VENDEDOR As Long = 1991
Public Const ID_ITEM_REL_GRAFICO4_VENDA_PRODUTOS As Long = 1992
Public Const ID_ITEM_REL_GRAFICO5_COMPRA_FORNECEDORES As Long = 1993
Public Const ID_ITEM_REL_ESTRATEGICO_AVISO_AQUISICAO As Long = 1994
Public Const ID_ITEM_REL_GRAFICO6_VENDA_CLIENTES As Long = 1995
Public Const ID_ITEM_REL_CR_LANCAMENTOS_DATA_EMISSAO As Long = 1996
Public Const ID_ITEM_REL_EXPORTA_CLIENTES_PRODUTO As Long = 1997
